name: CI
on:
  pull_request:
    branches:
      - "develop"
env:
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install dev Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Code Linting
        run: npm run lint

  test_frontend:
    name: Test Frontend code
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install dev Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      - name: Code Testing
        run: npm run test:ci
  # test_backend:
  #   name: Test Backend code
  #   needs: linting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: Code Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dev Dependencies
  #       run: npm install --legacy-peer-deps

  #     - name: Install Dependencies
  #       run: npm ci --legacy-peer-deps
  #     - name: Code Testing
  #       run: npm run test:ci
